[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.19.3"
  NODE_ENV = "production"

# API Rewrites for Backend (Render) - Update this URL to match your Render deployment
[[redirects]]
  from = "/api/*"
  to = "https://coogi-backend-7yca.onrender.com/api/:splat"
  status = 200
  force = true

# Direct backend health check
[[redirects]]
  from = "/health"
  to = "https://coogi-backend-7yca.onrender.com/"
  status = 200

# SPA Fallback for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
