[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.19.3"

# API Rewrites for Backend
[[redirects]]
  from = "/api/*"
  to = "https://coogi-backend-7yca.onrender.com/api/:splat"
  status = 200

# SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
